version: '3.8'
services:
  userservice:
    image: khshanovskyi/mockuserservice:latest
    ports:
      - "8041:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - GENERATE_USERS=true
      - USER_COUNT=1000
    volumes:
      - ./data:/app/data  # Optional: persist database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ums-mcp-server:
    depends_on:
      - userservice
    image: khshanovskyi/ums-mcp-server:latest
    ports:
      - "8005:8005"
    environment:
      - USERS_MANAGEMENT_SERVICE_URL=${USERS_MANAGEMENT_SERVICE_URL:-http://host.docker.internal:8041}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8005/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis-ums:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "6380:5540"


volumes:
  redis-data:
    driver: local

